name: Android Fastlane With Firebase App Distribution WorkFlow #optional
on:
 push:
  branches:
   -main
jobs:
 distribute_to_firebase: #optional workflow name
  runs-on: ubuntu-latest # when we distribute android
  steps:
  - name: check my rebo code #optional
    uses: actions/checkout@v2

  - name: Setup JDK 11 #optional
    uses: actions/setup-java@v2
    with: 
     java-version: '11'
     distribution: 'temurin'

  - name: Install Flutter #optional
    uses: subosito/flutter-action@v2

  - name: Setup Ruby #optional
    uses: ruby/setup-ruby@v2
    with: 
     ruby-version: '3.2.2'
     bundler-cache: true #make work flow faster
     working-directory: android # navigate to android folder
  - name: Build And Distribute App
    env:
      FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
    run: |
        bundle exce fastlane android firebase_distribution
    working-directory: android