
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
     firebase_app_distribution(
      app: "1:184764594253:android:3eca430ddbbfcd8924c404",
      firebase_cli_token: "1//03R6TKF4pCj2gCgYIARAAGAMSNwF-L9IrfIJRr4uK128d_lTrpboUAYJRW0klcUGJKQRJfH8NguTXaSZvn3iUqyVBQjg7YwuxpXo",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "molotfy003@gmail.com",
      release_notes: "First Fastlane Firebase Distribution"
    )
  end
end
